version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres-backend
    environment:
      POSTGRES_USER: postgres       # Change to desired username
      POSTGRES_PASSWORD:        # Change to desired password
      POSTGRES_DB: backend                # Change to desired database name
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
